language: python
sudo: false

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - pypy

env:
  - CELERY='<4'
  - CELERY='>=4'

install:
  - pip install mock pytest pytest-cov
  - pip install .
  - pip install celery$CELERY

script:
  - pytest --cov=pyramid_celery --cov-report= --cov-append

after_success:
  - coveralls
